#!/bin/bash

# Check if a parameter is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <systemd|container>"
    exit 1
fi

if [[ "$1" != "systemd" && "$1" != "container" ]]; then
    echo "Error: Invalid option '$1'."
    echo "Usage: $0 <systemd|container>"
    exit 1
fi

# Get the first parameter
PARAM=$1

# Check the virtual environment exists
if [ ! -d ".venv" ]; then
    echo "Python virtual environment not found. Creating a new one..."
    python3 -m venv .venv

    # Activate the virtual environment
    source .venv/bin/activate    

    # Install required packages
    echo "Installing required packages from requirements.txt..."
    pip install -r requirements.txt  
    if [ $? -ne 0 ]; then
        echo "Failed to install required packages. Please check requirements.txt."
        exit 1
    fi
    echo "Required packages installed successfully."
else
    source .venv/bin/activate    
fi

# Run the python setup script
echo "Running setup script (setup.py) ..."
.venv/bin/python setup.py $PARAM

