#!/bin/bash
#---------------------------------------------------------------------------------
# Copyright (c) 2025 Lancaster University
# Written by: Gerard Hand
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#---------------------------------------------------------------------------------
#
# This script removes the files created by the setup script.

if [ "$EUID" -ne 0 ]; then
    USERTXT="--user"
    SYSTEMD_PATH="$HOME/.config/systemd/user/xrootdrestart.service"
    CONFIG_DIR="$HOME/.config/xrootdrestart"
else
    USERTXT=""
    SYSTEMD_PATH="/etc/systemd/system/xrootdrestart.service"
    CONFIG_DIR="/etc/xrootdrestart"
fi

echo "Removing systemd service - xrootdrestart"
systemctl $USERTXT stop xrootdrestart
systemctl $USERTXT disable xrootdrestart
rm $SYSTEMD_PATH
systemctl $USERTXT daemon-reload

echo "Removing python virtual environment"
rm -Rf .venv

echo "Removing container"
podman rm xrootdrestart

echo "Removing container image"
podman rmi xrootdrestart

echo "Removing config and keys"
rm -Rf $CONFIG_DIR

echo "Clearing log file"
echo "Logfile cleared" > /var/log/xrootdrestart.log


